### ISSUE TITLE
The Tensorflow wrapper?

### ISSUE THREAD

**Issue by alanhsu5678** [neurosim/DNN_NeuroSim_V1.1#1]
Hi,

In v1.1, the wrapper of Tensorflow doesn't exist.
Could we use Inference_tensorflow from v1.0 directly?

Or will you upload the folder Inference_tensorflow for v1.1 in the future?

Thanks!

Alan

**Comment by neurosim** [comment]
Hi, the tensorflow version is currently not available for V1.1, we will upload that in the future.
