### ISSUE TITLE
How your framework support resnet?

### ISSUE THREAD

**Issue by qusongyun** [neurosim/DNN_NeuroSim_V1.1#3]
Hello, thank you for doing such an excellent job.
I noticed that you mentioned resnet in your paper, can your framework support the simulation of resnet? I did not find the relevant code. I wonder how your framework support the skip connect structure in resnet.

**Comment by neurosim** [comment]
Hi, the user can modify the network structure in python wrapper to resnet, while in hardware design, the skip connection is considered as element-wise addition between two layers, which involves global-level buffer accessing and operation of accumulation units, the user can simply modify the codes accordingly in "chip.cpp" from NeuroSim core.
We will also release reconfigurable NeuroSim for different popular networks in the future.

**Comment by nustart0720** [comment]
> Hello, thank you for doing such an excellent job.
> I noticed that you mentioned resnet in your paper, can your framework support the simulation of resnet? I did not find the relevant code. I wonder how your framework support the skip connect structure in resnet.

Hi, recently, I also want to map the resnet model onto the simulator. Have you already managed to modify "chip.cpp" to support resnet?
